summary: List of sources
value:
  pagination:
    order_by: created_at
    dir: desc
    limit: 1
    next: src_2Q0cNXCHyzPJCUOmpk76JKeU
  count: 1
  models:
    - id: src_2Q0cNXCHyzPJCUOmpk76JKeU
      team_id: tm_nlcetVe8k1lMAY0KR0OxNuHr
      archived_at: null
      updated_at: '2021-08-01T21:48:16.865Z'
      created_at: '2021-08-01T21:45:07.100Z'
      name: test
      url: https://events.hookdeck.com/e/src_2Q0cNXCHyzPJCUOmpk76JKeU
